env:
  browser: true
  es2021: true
  node: true
  es6: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2016
  sourceType: module
plugins:
  - prettier
  - react
  - '@typescript-eslint'
  - 'unused-imports'
rules:
  eqeqeq: error
  prettier/prettier:
    - error
  react/react-in-jsx-scope: 'off'
  react/no-unescaped-entities: 'off'
  react/prop-types: 'off'
  unused-imports/no-unused-imports-ts: 2
settings:
  react:
    version: detect
