- op: replace
  path: /data/nginx.conf
  value: |
    error_log /dev/stdout info;
    events {}
    http {
      access_log         /dev/stdout;
      include            /etc/nginx/mime.types;
      default_type       application/octet-stream;
      keepalive_timeout  65;
      server {
        listen              9001;
        root                /usr/share/nginx/html;

        location / {
          add_header Last-Modified $date_gmt;
          add_header Cache-Control 'no-store, no-cache';
          if_modified_since off;
          expires off;
          etag off;
        }
      }
    }

