apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: activemq-artemis-self-provisioning-plugin
spec:
  displayName: 'OpenShift Console ActiveMQ Artemis Self Provisioning Plugin'
  # i18n:
  #   loadType: Preload
  backend:
    type: Service
    service:
      name: activemq-artemis-self-provisioning-plugin
      namespace: activemq-artemis-self-provisioning-plugin
      port: 9443
      basePath: '/'
  proxy:
    - type: Service
      alias: api-server-service
      authorization: UserToken
      endpoint:
        type: Service
        service:
          name: activemq-artemis-jolokia-api-server
          namespace: activemq-artemis-jolokia-api-server
          port: 9443
