apiVersion: v1
kind: Secret
metadata:
  name: builder-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: builder
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: default-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: default
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: deployer-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: deployer
type: kubernetes.io/service-account-token
