/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { ApiResponse } from '../models/ApiResponse';

import type { CancelablePromise } from '../core/CancelablePromise';
import { OpenAPI } from '../core/OpenAPI';
import { request as __request } from '../core/request';

export class DevelopmentService {
  /**
   * the api info
   * **Show all exposed paths on the api server**
   *
   * The return value is a json object that contains
   * description of all api paths defined in the api server.
   *
   * **Example:**
   *
   * **Request url:** https://localhost:9443/api/v1/api-info
   * **Response:**
   * ```json
   * {
   * "message": {
   * "info": {
   * "name": "The Jolokia Api Server\n(Generated by `yarn build-api-doc`.)\n",
   * "description": ...(text omitted for brevity)
   * "version": "1.0.0-alpha"
   * },
   * "paths": {
   * "post": [
   * "/api/v1/jolokia/login",
   * "/api/v1/execBrokerOperation"
   * ],
   * "get": [
   * "/api/v1/brokers",
   * "/api/v1/brokerDetails",
   * "/api/v1/readBrokerAttributes",
   * "/api/v1/brokerComponents",
   * "/api/v1/addresses",
   * "/api/v1/queues",
   * "/api/v1/queueDetails",
   * "/api/v1/addressDetails",
   * "/api/v1/acceptors",
   * "/api/v1/acceptorDetails",
   * "/api/v1/api-info"
   * ]
   * }
   * },
   * "status": "successful"
   * }
   * ```
   *
   * @returns ApiResponse Success
   * @throws ApiError
   */
  public static apiInfo(): CancelablePromise<ApiResponse> {
    return __request(OpenAPI, {
      method: 'GET',
      url: '/api-info',
    });
  }
}
