apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: console-oauth-client-https
parameters:
  - name: OAUTH_SECRET
    generate: expression
    from: "[a-zA-Z0-9]{40}"
  - name: REDIRECT_URL
    value: https://localhost:9442/auth/callback
    required: true
objects:
  - apiVersion: oauth.openshift.io/v1
    kind: OAuthClient
    metadata:
      name: console-oauth-client-https
    grantMethod: auto
    secret: ${OAUTH_SECRET}
    redirectURIs:
    - ${REDIRECT_URL}
